
# fastDFS
fdfs:
  connect-timeout: 300  # 连接超时时间
  so-timeout: 300       # 读取超时时间
  tracker-list: 101.132.123.185:22122

spring:
  application:
    name: katouyi-tools
  redisson:
    hostPort: 101.132.123.185:6379
  redis:
    host: 101.132.123.185
    port: 6379
    database: 0
    password:

#redis:
#  cluster:
#  hosts: 101.132.123.185
#  port: 6379
#  password:

logging:
  level:
    root: error
    io.netty.buffer.PoolThreadCache: INFO

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: newProducer

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: /metrics